services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      # depends_on:
      # - be-tierlists
      # - be-tierlistitems
    networks:
      - public-network

networks:
  public-network:
    driver: bridge
  backend-network:
    driver: bridge
  sso-network:
    driver: bridge
  db-network:
    driver: bridge
