@startuml
actor EndUserAPI
participant "APIGateway" as APIGateway
participant "BE-Tierlists" as BackendLists
participant "BE-TierlistItems" as BackendItems
participant "MySQL\nDataBaseEngine" as MySQL

EndUserAPI -> APIGateway : HTTP 8000
APIGateway -> BackendLists : GET /tierlists/id
BackendLists -> MySQL : SQL Query
BackendLists <-- MySQL : SQL Data
BackendLists -> BackendItems : GET /tierlists/id/items
BackendItems -> MySQL : SQL Query
BackendItems <-- MySQL : SQL Data
BackendItems --> BackendLists : Tierlist items (JSON)
BackendLists --> APIGateway : Tierlist (JSON)
APIGateway --> EndUserAPI : Tierlist (JSON)
@enduml

# Responsabilities

## APIGateway

Entry point of our group docker environment
Will steer requests to the correct micro service

## BE-Tierlists

Receives the http get requests and process it to return a valid json response

## DB Engine

Processes the sql queries from the BE and stores our data.
